# Generated by Django 5.0.6 on 2024-06-10 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_transactions', '0002_transaction_method_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Miqdori'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='method',
            field=models.CharField(choices=[('card', 'Kartadan'), ('cash', 'Naqd pul'), ('click', 'Click')], max_length=5, verbose_name='Usuli'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'Kirim'), ('expense', 'Chiqim')], max_length=7, verbose_name='Turi'),
        ),
    ]
